### SIGN UP
POST http://localhost:3003/signup
Content-Type: application/json

{
    "name": "Rodrigo Silva",
    "email": "rodrigo.silva@email.com",
    "password": "123456",
    "role": "normal"
}

### LOGIN
POST http://localhost:3003/login
Content-Type: application/json

{
   "email": "rodrigo.silva@email.com" ,
   "password": "123456"
}

### GET PROFILE
GET http://localhost:3003/user/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFjZDBiYjAzLTVlYzgtNDcwNi1hOTBlLWIzZDY5NmFjYWU3OCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY3NjUwMDk4MSwiZXhwIjoxNjc2NTA0NTgxfQ.AJsg4iI0nGo9Y5ltlStuIm4FVX6KXL1nD2XqMNTf3w8

### GET USER
GET http://localhost:3003/user/415386d2-f880-493d-bb14-4442140f7f7c
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFjZDBiYjAzLTVlYzgtNDcwNi1hOTBlLWIzZDY5NmFjYWU3OCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY3NjUwMDk4MSwiZXhwIjoxNjc2NTA0NTgxfQ.AJsg4iI0nGo9Y5ltlStuIm4FVX6KXL1nD2XqMNTf3w8

### CREATE RECIPE
POST http://localhost:3003/recipe
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFjZDBiYjAzLTVlYzgtNDcwNi1hOTBlLWIzZDY5NmFjYWU3OCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY3NjUwMDk4MSwiZXhwIjoxNjc2NTA0NTgxfQ.AJsg4iI0nGo9Y5ltlStuIm4FVX6KXL1nD2XqMNTf3w8
Content-Type: application/json

{
    "title": "Bolo de chocolate",
    "description": "bolo feito com farinha, cacau em pó e fermento"
}

### GET RECIPE
GET http://localhost:3003/recipe/37057171-0126-471c-b9bf-6576258f7c19
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFjZDBiYjAzLTVlYzgtNDcwNi1hOTBlLWIzZDY5NmFjYWU3OCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY3NjUwMDk4MSwiZXhwIjoxNjc2NTA0NTgxfQ.AJsg4iI0nGo9Y5ltlStuIm4FVX6KXL1nD2XqMNTf3w8

### FOLLOW ANOTHER USER
POST http://localhost:3003/follow/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxNTM4NmQyLWY4ODAtNDkzZC1iYjE0LTQ0NDIxNDBmN2Y3YyIsInJvbGUiOiJub3JtYWwiLCJpYXQiOjE2NzY1MDMzNjYsImV4cCI6MTY3NjUwNjk2Nn0.ZC4nl3hFOM4r6g7K8u9r66XGHh0Qg471DVb51ITJHqU
Content-Type: application/json

{
    "userToFollowId": "acd0bb03-5ec8-4706-a90e-b3d696acae78"
}

### UNFOLLOW ANOTHER USER
DELETE http://localhost:3003/follow/delete/415386d2-f880-493d-bb14-4442140f7f7c
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFjZDBiYjAzLTVlYzgtNDcwNi1hOTBlLWIzZDY5NmFjYWU3OCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY3NjUwMDk4MSwiZXhwIjoxNjc2NTA0NTgxfQ.AJsg4iI0nGo9Y5ltlStuIm4FVX6KXL1nD2XqMNTf3w8

### GET RECIPES FEED
GET http://localhost:3003/user/feed
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxNTM4NmQyLWY4ODAtNDkzZC1iYjE0LTQ0NDIxNDBmN2Y3YyIsInJvbGUiOiJub3JtYWwiLCJpYXQiOjE2NzY1MDMzNjYsImV4cCI6MTY3NjUwNjk2Nn0.ZC4nl3hFOM4r6g7K8u9r66XGHh0Qg471DVb51ITJHqU