### SIGN UP
POST http://localhost:3003/signup
Content-Type: application/json

{
    "name": "Rodrigo Silva",
    "email": "rodrigo.silva@email.com",
    "password": "123456"
}

### LOGIN
POST http://localhost:3003/login
Content-Type: application/json

{
   "email": "jose.ferreira@email.com" ,
   "password": "123456"
}
### GET USER
GET http://localhost:3003/user/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVhNzdiNWZhLWRlZDctNDZkNy04OTJiLTExZjc5ZTJjM2Q5NSIsImlhdCI6MTY3NjM3ODM0NSwiZXhwIjoxNjc2MzgxOTQ1fQ.jB-t2YwoakiwNfBkjnHIJNHBk3ZDZUbrjTMfFJi9ggM
